[package]
name = "vulkan-christmas-tree"
version = "0.1.0"
authors = ["Jacek Bilski <jacek@bilski.tech>"]
edition = "2018"

[dependencies]
vulkano = "0.19.0"
vulkano-shaders = "0.19.0"
winit = "0.22.2"
vulkano-win = "0.19.0"
