[package]
name = "vulkan-christmas-tree"
version = "0.1.0"
authors = ["Jacek Bilski <jacek@bilski.tech>"]
edition = "2021"

[features]
default = []
validation-layers = []

[dependencies]
ash = "0.32.0"
cgmath = "0.18.0"
winit = "0.24.0"
memoffset = "0.6.1"
rand = {version = "0.8.3", features = ["small_rng"]}
tobj = "2.0.4"

[build-dependencies]
shaderc = "0.7.2"

[dev-dependencies]
rstest = "0.6.4"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.9", features = ["windef", "libloaderapi"] }
