[package]
name = "vulkan-christmas-tree"
version = "0.1.0"
authors = ["Jacek Bilski <jacek@bilski.tech>"]
edition = "2018"

[dependencies]
ash = "0.31.0"
cgmath = "0.17.0"
winit = "0.23.0"
memoffset = "0.6.1"
tobj = "2.0.2"

[build-dependencies]
shaderc = "0.6.2"

[dev-dependencies]
rstest = "0.6.3"
