[package]
name = "vulkan-christmas-tree"
version = "0.1.0"
authors = ["Jacek Bilski <jacek@bilski.tech>"]
edition = "2021"

[features]
default = []
validation-layers = []

[dependencies]
ash = "0.34.0+1.2.203"
ash-window = "0.8.0"
raw-window-handle = "0.4.2"
cgmath = "0.18.0"
winit = "0.25.0"
memoffset = "0.6.4"
rand = {version = "0.8.4", features = ["small_rng"]}
tobj = "3.2.0"

[build-dependencies]
shaderc = "0.7.3"

[dev-dependencies]
rstest = "0.11.0"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.9", features = ["windef", "libloaderapi"] }
